### ISSUE TITLE
Xaml designer NullReferenceException 

### ISSUE THREAD

**Issue by mjmeans** [Windows-XAML/Template10#1597]
The XAML designer throws an error when I set the project min version and target version to Build 16299 with Template10 version 1.1.13-preview-20171207 and VS 2017 Community v15.5.0.
```
System.NullReferenceException: Object reference not set to an instance of an object.
at Template10.Controls.HamburgerMenu.get_NavButtonCount()
   at Template10.Controls.HamburgerMenu.get_AllNavButtonsAreLoaded()
   at Template10.Controls.HamburgerMenu.NavButton_Loaded(Object sender, RoutedEventArgs e)
```

**Comment by johnthomaswarner** [comment]
I am having this issue as well, although I'm not sure what the cause is.  Is there a solution?

System.NullReferenceException: Object reference not set to an instance of an object.
at Template10.Controls.HamburgerMenu.get_NavButtonCount()
   at Template10.Controls.HamburgerMenu.get_AllNavButtonsAreLoaded()
   at Template10.Controls.HamburgerMenu.NavButton_Loaded(Object sender, RoutedEventArgs e)

**Comment by riesm** [comment]
Exact same problem, but now using VS 15.8.3. This happens when opening the shell.xaml page in Visual Studio.

**Comment by akreft** [comment]
@JerryNixon Is there a resolution to this issue? I am using Visual Studio 2017 with Template10 version 1.1.12. The hamburger template out of the box has this error so the Shell.xaml file cannot be viewed in design mode. Thank you.

**Comment by mjmeans** [comment]
I am no longer having this problem, but too many changes have happened since I reported it to know what specifically solved the issue.
