### ISSUE TITLE
Newtonsoft 12.0.2 causing crash in 1.1.12

### ISSUE THREAD

**Issue by lars-alfonse** [Windows-XAML/Template10#1713]
AppCenter forced an update to Newtonsoft 12.0.2 which caused Template10 to error.
method not found at Template10.Services.SerializationService.JsonSerializationService..ctor() at Template10.Services.SerializationService.SerializationService.get_Json() at Template10.Services.NavigationService.NavigationService..ctor(Frame frame) at Template10.Common.BootStrapper.

**Comment by lars-alfonse** [comment]
Exception: Method not found: 'Void Newtonsoft.Json.JsonSerializerSettings.set_TypeNameAssemblyFormat(System.Runtime.Serialization.Formatters.FormatterAssemblyStyle)'.
Stacktrace: 
at Template10.Services.SerializationService.JsonSerializationService..ctor()
   at Template10.Services.SerializationService.SerializationService.get_Json()
   at Template10.Services.NavigationService.NavigationService..ctor(Frame frame)
   at Template10.Common.BootStrapper.NavigationServiceFactory(BackButton backButton, ExistingContent existingContent, Frame frame)
   at Tiller.CRM.App.CreateRootElement(IActivatedEventArgs e) in C:\Users\nrogers\Documents\Tiller.CRM\src\Tiller.CRM\App.xaml.cs:line 200
   at Template10.Common.BootStrapper.<StartupOrchestratorAsync>d__112.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.WinRTSynchronizationContextBase.Invoker.InvokeCore()

**Comment by jp-weber** [comment]
The code of the 1.1.12 has not been touched since ages. If the switch to the new 2.0 version means too much work, I would recommend a fork. For the Unigram project there use a Template10 fork, based on an old version. This fork works fine.
https://github.com/FrayxRulez/Unigram.Infrastructure

**Comment by lars-alfonse** [comment]
Thanks for the response! This will work for me! Thank you so much!

**Comment by robertmclaws** [comment]
@JerryNixon This is still an issue with the libraries. Any chance for a new release? Thanks!
