### ISSUE TITLE
VungleAd Completion Causes Windows.UI.Xaml.UnhandledExceptionEventArgs

### ISSUE THREAD

**Issue by kdowswell** [Windows-XAML/Template10#485]
After viewing a full screen video ad using VungleAdSdk I get the following exception when closing the ad with the top left (x) button.

Exception:
{Windows.UI.Xaml.UnhandledExceptionEventArgs}

Message:
"System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
at Template10.Controls.HamburgerMenu.NavButton_Loaded(Object sender, RoutedEventArgs e)"

 https://vungle.com/

**Comment by JerryNixon** [comment]
I don't know this SDK. If you can give me more information I will try to help. If you figure it out, and if it can be generalized, please submit a Pull Request to this repo.
