### ISSUE TITLE
CalculateBackVisibility Exception 

### ISSUE THREAD

**Issue by ozzy1873** [Windows-XAML/Template10#495]
Not sure if this is a duplicate:

Exception:
System.UnauthorizedAccessException: Access is denied. (Excep_FromHResult 0x80070005)
   at SharedLibrary!<BaseAddress>+0x375c4d
   at SharedLibrary!<BaseAddress>+0x3b9f09
   at SharedLibrary!<BaseAddress>+0x3fc879
   at SharedLibrary!<BaseAddress>+0x3fc7fb
   at SharedLibrary!<BaseAddress>+0x3fc7b7
   at SharedLibrary!<BaseAddress>+0x3fccb1
   at SharedLibrary!<BaseAddress>+0x3fcc9d
   at Template10.Behaviors.NavButtonBehavior.CalculateBackVisibility(UI.Xaml.Controls.Frame frame)
   at Template10.Behaviors.NavButtonBehavior.Calculate(Boolean allow)
   at Template10.Behaviors.NavButtonBehavior.Attach(UI.Xaml.DependencyObject associatedObject)
   at Microsoft.Xaml.Interactivity.BehaviorCollection.Attach(UI.Xaml.DependencyObject associatedObject)
   at Microsoft.Xaml.Interactivity.Interaction.FrameworkElement_Loaded(Object sender, UI.Xaml.RoutedEventArgs e)
   at SharedLibrary!<BaseAddress>+0x7e475b
   at SharedLibrary!<BaseAddress>+0xadf933
   at SharedLibrary!<BaseAddress>+0x7e1e39
   at SharedLibrary!<BaseAddress>+0x7e224d
   at SharedLibrary!<BaseAddress>+0x7e21a1
   at SharedLibrary!<BaseAddress>+0x89a7ab
   at SharedLibrary!<BaseAddress>+0x89a795
   at RadarRabbit.App.CoreApplication_UnhandledErrorDetected(Object sender, ApplicationModel.Core.UnhandledErrorDetectedEventArgs e)
Stack Trace:
   at SharedLibrary!<BaseAddress>+0x375c4d
   at SharedLibrary!<BaseAddress>+0x3b9f09
   at SharedLibrary!<BaseAddress>+0x3fc879
   at SharedLibrary!<BaseAddress>+0x3fc7fb
   at SharedLibrary!<BaseAddress>+0x3fc7b7
   at SharedLibrary!<BaseAddress>+0x3fccb1
   at SharedLibrary!<BaseAddress>+0x3fcc9d
   at Template10.Behaviors.NavButtonBehavior.CalculateBackVisibility(UI.Xaml.Controls.Frame frame)
   at Template10.Behaviors.NavButtonBehavior.Calculate(Boolean allow)
   at Template10.Behaviors.NavButtonBehavior.Attach(UI.Xaml.DependencyObject associatedObject)
   at Microsoft.Xaml.Interactivity.BehaviorCollection.Attach(UI.Xaml.DependencyObject associatedObject)
   at Microsoft.Xaml.Interactivity.Interaction.FrameworkElement_Loaded(Object sender, UI.Xaml.RoutedEventArgs e)
   at SharedLibrary!<BaseAddress>+0x7e475b
   at SharedLibrary!<BaseAddress>+0xadf933
   at SharedLibrary!<BaseAddress>+0x7e1e39
   at SharedLibrary!<BaseAddress>+0x7e224d
   at SharedLibrary!<BaseAddress>+0x7e21a1
   at SharedLibrary!<BaseAddress>+0x89a7ab
   at SharedLibrary!<BaseAddress>+0x89a795
   at RadarRabbit.App.CoreApplication_UnhandledErrorDetected(Object sender, ApplicationModel.Core.UnhandledErrorDetectedEventArgs e)

**Comment by ozzy1873** [comment]
Looks like this may be getting called on a non-UI thread.

**Comment by JerryNixon** [comment]
I have never seen this. Please provide a repro.

**Comment by ozzy1873** [comment]
I never see it either, but I get it from apps in the field fairly often. Pretty hard to fix if we can't duplicate it.

I'll dig into it a bit...

**Comment by ozzy1873** [comment]
This looks like a potential null reference exception when f == null. I have not seen this exception, so I suspect those event handlers are never getting wired up. Not sure if this is related or should be a separate bug:

```
private static void FrameChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
    {
        var b = (d as NavButtonBehavior);
        var f = e.NewValue as Frame;
        if (f == null)
        {
            b._goBackReg = f.RegisterPropertyChangedCallback(Frame.CanGoBackProperty, (s, args) => b.Calculate(true));
            b._goForwardReg = f.RegisterPropertyChangedCallback(Frame.CanGoForwardProperty, (s, args) => b.Calculate(true));
            f.SizeChanged += b.SizeChanged;
            f.LayoutUpdated += b.LayoutUpdated;
        }
        b.Calculate(true);
    }
```

**Comment by JerryNixon** [comment]
Code looks correct. What's the issue?

**Comment by ozzy1873** [comment]
If f is null, isn't a null reference exception thrown?

**Comment by JerryNixon** [comment]
No.

**Comment by JerryNixon** [comment]
@ozzy1873, sorry for the confusion. Daren just pointed out to me that I read the code backwards. :) No kidding. Sorry for the confusion.

**Comment by ghost** [comment]
The problem is still appearing in 1.1.2. I can't reproduce it by myself, but there are many crash reports.
Here is the stack trace:

```
   at SharedLibrary!<BaseAddress>+0x375c4d
   at SharedLibrary!<BaseAddress>+0x3b9f09
   at SharedLibrary!<BaseAddress>+0x3fc879
   at SharedLibrary!<BaseAddress>+0x3fc7fb
   at SharedLibrary!<BaseAddress>+0x3fc7b7
   at SharedLibrary!<BaseAddress>+0x3fccb1
   at SharedLibrary!<BaseAddress>+0x3fcc9d
   at Template10.Behaviors.NavButtonBehavior.CalculateBackVisibility(UI.Xaml.Controls.Frame frame)
   at Template10.Behaviors.NavButtonBehavior.Calculate(Boolean allow)
   at Template10.Behaviors.NavButtonBehavior.LayoutUpdated(Object sender, Object e)
   at SharedLibrary!<BaseAddress>+0x3af68d
```

**Comment by ghost** [comment]
Same thing here!
Access is denied. (Excep_FromHResult 0x80070005)
