### ISSUE TITLE
Help needed: how to implement PinDialog

### ISSUE THREAD

**Issue by frostieDE** [Windows-XAML/Template10#526]
I am currently trying to port my app to UWP using Template10, but there is one thing left: I've implemented some sort of pin dialog. Basically, everytime you resume the app, you first need to enter a pin to grand access. 

Requirements:
- the pin dialog is optional
- navigation is restored after you entered the correct pin

I managed to implement it the following way: In my `App.xaml.cs` I have a event handler for the VisibilityChanged event of the current `Window`.

``` c#
private void OnVisibilityChanged(object sender, Windows.UI.Core.VisibilityChangedEventArgs e)
        {
            var navigationService = base.NavigationService;

            if(pinFrame == null)
            {
                pinFrame = new Frame();
            }

            if(!PinHelper.IsPinActive() || !e.Visible)
            {
                return;
            }

            if (Window.Current.Content != pinFrame)
            {
                restore = Window.Current.Content;
            }

            if (Window.Current.Content != pinFrame)
            {
                Window.Current.Content = pinFrame;
            }

            if (!(pinFrame.CurrentSourcePageType == typeof(EnterPinDialog)))
            {
                pinFrame.Navigate(typeof(EnterPinDialog));
                var dialog = pinFrame.Content as EnterPinDialog;
                dialog.Granted += delegate
                {
                    Window.Current.Content = restore;
                    pinFrame = null;
                    restore = null;
                };
            }
        }
```

The only problem is, that when calling `Windows.Current.Content = restore` an exception is thrown:

```
System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Template10.Controls.HamburgerMenu.NavButton_Loaded(Object sender, RoutedEventArgs e)
```

So my final questions are
- should we fix the loaded event (this should not be hard)
- is there maybe a better way to implement my feature? :)

**Comment by JerryNixon** [comment]
Have you looked at the Login project in Samples?
