### ISSUE TITLE
Error in Minimal - System.ArgumentNullException - pUnk cannot be null

### ISSUE THREAD

**Issue by rickengle** [Windows-XAML/Template10#573]
Occasionally when I load my Minimal project the designer in VS 2015 or Blend gives me this error:

System.ArgumentNullException
Value cannot be null.
Parameter name: pUnk
   at System.Runtime.InteropServices.Marshal.Release(IntPtr pUnk)
   at Microsoft.VisualStudio.DesignTools.DesignerHost.HostServices.HostTextBufferService.<>c__DisplayClass38_0.<Microsoft.VisualStudio.DesignTools.DesignerHost.HostServices.IHostTextBufferProvider.GetTextBuffer>b__0()
   at Microsoft.VisualStudio.DesignTools.DesignerContract.Isolation.Remoting.ThreadMarshaler.<>c__DisplayClass47_0`1.<MarshalIn>b__0()
   at Microsoft.VisualStudio.DesignTools.DesignerContract.Isolation.Remoting.STAMarshaler.Call.InvokeWorker()
   at Microsoft.VisualStudio.DesignTools.DesignerContract.Isolation.Remoting.STAMarshaler.Call.Invoke(Boolean waitingInExternalCall)
   at Microsoft.VisualStudio.DesignTools.DesignerContract.Isolation.Remoting.STAMarshaler.InvokeCall(Call call)

Clicking  to reload the designer fixes it but why would this keep happening?

  Rick

**Comment by JerryNixon** [comment]
pUnk?

**Comment by rickengle** [comment]
I don't know what that is but the full error is pasted above, its from System.Runtime.InteropServices.Marshal.Release(IntPtr pUnk).

**Comment by JerryNixon** [comment]
This is unlikely Template 10. I cannot duplicate this. If you figure out a repro, let me know.
