### ISSUE TITLE
Frame.Navigate() broken

### ISSUE THREAD

**Issue by takacsalbert** [Windows-XAML/Template10#586]
Latest release (v1.1.1) contains a bug related to framework standard Frame.Navigate() method. We use this method to navigate from a page code behind. When we pass a parameter to the target, a serialization exception is raised.
Please see the exception below:

```
Newtonsoft.Json.JsonReaderException occurred
  HResult=-2146233088
  LineNumber=0
  LinePosition=0
  Message=Unexpected character encountered while parsing value: O. Path '', line 0, position 0.
  Path=""
  Source=Newtonsoft.Json
  StackTrace:
       at Newtonsoft.Json.JsonTextReader.ParseValue()
       at Newtonsoft.Json.JsonTextReader.Read()
       at Newtonsoft.Json.JsonReader.ReadAndMoveToContent()
       at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
       at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
       at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
       at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
       at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
       at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
       at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
       at Template10.Services.SerializationService.JsonSerializationService.Deserialize(String value)
       at Template10.Services.NavigationService.FrameFacade.FacadeNavigatingCancelEventHandler(Object sender, NavigatingCancelEventArgs e)
       at Template10.Services.NavigationService.FrameFacade.<.ctor>b__1_1(Object s, NavigatingCancelEventArgs e)
       at Windows.UI.Xaml.Controls.Frame.Navigate(Type sourcePageType, Object parameter)
       at Sample.Views.SamplePage.Button_Click(Object sender, ItemClickEventArgs e)
  InnerException: 
```

We've been investigated this in the source code and it seems to be that recent changes work for NavigationService.Navigate(), but not for Frame.Navigate(). We think that the difference is between the two is that NavigationService serializes the parameter, but of course the standard Frame.Navigate does not. We could serialize it before passing to the target, but it seems the Container class is an internal class inside JsonSerializationService. Please advise. Thank you for your support.

**Comment by JerryNixon** [comment]
Yes. This is right. Please upgrade to 1.1.3
