### ISSUE TITLE
Exception when suspending/resuming on W10M - Value does not fall within the expected range.

### ISSUE THREAD

**Issue by darshanrampatel** [Windows-XAML/Template10#675]
Hi,

I am using Template 10 NuGet Version 1.0.14 (though I was seeing this on previous versions on Template10) and am seeing the following behaviour when I perform the below actions on my Windows 10 Mobile device:
1. Run the App
2. Press the Windows Home button (takes me back to the Start screen)
3. Run the App again

What happens is that the app fails to start, with an exception of:
`Value does not fall within the expected range.`

Call Stack:

```
  at Windows.UI.Xaml.Controls.ContentControl.put_Content(Object value)
   at Template10.Common.BootStrapper.NavigationServiceFactory(BackButton backButton, ExistingContent existingContent, Frame frame)
   at Template10.Common.BootStrapper.NavigationServiceFactory(BackButton backButton, ExistingContent existingContent)
   at MyApp.App.OnInitializeAsync(IActivatedEventArgs args)
   at Template10.Common.BootStrapper.<InitializeFrameAsync>d__77.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Template10.Common.BootStrapper.<InternalLaunchAsync>d__53.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Threading.WinRTSynchronizationContext.Invoker.InvokeCore()
```

This doesn't happen if I am in debug mode in Visual Studio and use the lifestyle events to Suspend/Resume. This happens on all pages of my app (I am using the Hamburger menu control).

I am not sure how to investigate this further? Any ideas?

Note: this may be similar to #325, but I don't get to the Splash screen page.

Thanks.

@JerryNixon, please let me know if you'd rather this went on SO.

**Comment by JerryNixon** [comment]
I'm sorry, I can't remember that many version back.

**Comment by darshanrampatel** [comment]
@JerryNixon, sorry - typo'd the version I'm on! I'm using v1.1.4 (which is the latest Nuget version),

**Comment by SergioMorchon** [comment]
I have the same issue.

``` c#
public App()
        {
            InitializeComponent();
        }

 public override async Task OnInitializeAsync(IActivatedEventArgs args)
        {
            var nav = NavigationServiceFactory(BackButton.Attach, ExistingContent.Include);// here it breaks with "Value does not fall within the expected range".
```

Steps to reproduce:
1. Deploy on mobile.
2. From Visual Studio, Debug but not launch.
3. From Mobile, open the app. It will run normally.
4. From Mobile, press "back".
5. From Visual Studio, trigger the lifecycle event "Suspend".
6. From mobile, open the app from the main tile.
7. Enjoy the exception!

Why is this issue closed? Because the bug is still there :S

Edit (Solution!):
If you add:

``` c#
        private bool NeedsNewNavigationService(IActivatedEventArgs args)
        {
            switch (args.PreviousExecutionState)
            {
                case ApplicationExecutionState.ClosedByUser:
                case ApplicationExecutionState.NotRunning:
                case ApplicationExecutionState.Terminated:
                    return true;
                case ApplicationExecutionState.Running:
                case ApplicationExecutionState.Suspended:
                    return false;
            }
            return true;
        }
```

and check for it on the `OnInitializeAsync` App method _before_ create a new Window content, it will run ok :)

In my case:

``` c#
        private bool NeedsNewNavigationService(IActivatedEventArgs args)
        {
            switch (args.PreviousExecutionState)
            {
                case ApplicationExecutionState.ClosedByUser:
                case ApplicationExecutionState.NotRunning:
                case ApplicationExecutionState.Terminated:
                    return true;
                case ApplicationExecutionState.Running:
                case ApplicationExecutionState.Suspended:
                    return false;
            }
            return true;
        }

        public override async Task OnInitializeAsync(IActivatedEventArgs args)
        {
            InstallVoiceCommands();
            if (NeedsNewNavigationService(args))
            {
                var nav = NavigationServiceFactory(BackButton.Attach, ExistingContent.Include);

                if (Window.Current.Content is ModalDialog)
                {
                    Window.Current.Content = new ModalDialog
                    {
                        DisableBackButtonWhenModal = true,
                        Content = new Views.Shell(nav),
                        ModalContent = new Views.Busy()
                    };
                }
                else
                {
                    Window.Current.Content = new Views.Shell(nav);
                }
            }
            await Task.CompletedTask;
        }
```
