### ISSUE TITLE
Unable to cast object of type 'XxxxxViewModel' to type 'Template10.Services.NavigationService.INavigable'.

### ISSUE THREAD

**Issue by pellea** [Windows-XAML/Template10#697]
Hello,

In the latest release (1.1.5) I cannot use a view model without INavigable. I don't want to implement INavigable if I don't need to ...

Here is the stacktrace:

```
   at Template10.Services.NavigationService.NavigationService.ResolveForPage(Page page)
   at Template10.Services.NavigationService.NavigationService.<NavigateToAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Template10.Services.NavigationService.NavigationService.<>c__DisplayClass20_0.<<-ctor>b__2>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Template10.Common.DispatcherWrapper.<DispatchAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Template10.Services.NavigationService.NavigationService.<<-ctor>b__20_1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Threading.WinRTSynchronizationContext.Invoker.InvokeCore()
```

Regards,
Adrien.

**Comment by marcominerva** [comment]
Just inherit your ViewModel from ViewModelBase (that in turns implements INavigable).

**Comment by pellea** [comment]
I don't want to either! It's even worse ... 
It was working fine before.

**Comment by JerryNixon** [comment]
This was not an intended requirement. T10 will not require INav. Let me look into it.

**Comment by JerryNixon** [comment]
Exactly how is it preventing a standard view-model?

**Comment by JerryNixon** [comment]
You were right. I found the error. Fixed it. When I update NuGet today you will get the fix, too. Thanks for reporting this. We never want to force a developer to implement INav. 

Was doing this explicit conversion

``` csharp
return (INavigable)page.DataContext;
```

Should have been doing this implicit conversion

``` csharp
return page.DataContext as INavigable;
```
